defaults:
- search_mas_nosearch_external
- _self_

training:
  total_training_steps: 50
  project_name: orchrl
  experiment_name: search_mas_train_50step_memory_optimized
  logger:
  - console
  model_checkpoints_dir: checkpoints/search_mas_train_50step_memory_optimized
  train_batch_size: 6
  train_sample_num: 12
  validate_sample_num: 4
  val_freq: 10
  max_prompt_length: 3072
  max_response_length: 3072

models:
  model_0:
    ppo_trainer_config:
      data:
        max_prompt_length: 3072
        max_response_length: 3072
      actor_rollout_ref:
        actor:
          ppo_max_token_len_per_gpu: 6144
          ppo_micro_batch_size_per_gpu: 2
        ref:
          log_prob_micro_batch_size_per_gpu: 2
          log_prob_max_token_len_per_gpu: 6144
        rollout:
          temperature: 0.6
          prompt_length: 3072
          response_length: 3072
          max_num_batched_tokens: 6144
          max_num_seqs: 96
  model_1:
    ppo_trainer_config:
      data:
        max_prompt_length: 3072
        max_response_length: 3072
      actor_rollout_ref:
        actor:
          ppo_max_token_len_per_gpu: 6144
          ppo_micro_batch_size_per_gpu: 2
        ref:
          log_prob_micro_batch_size_per_gpu: 2
          log_prob_max_token_len_per_gpu: 6144
        rollout:
          temperature: 0.6
          prompt_length: 3072
          response_length: 3072
          max_num_batched_tokens: 6144
          max_num_seqs: 96
  model_2:
    ppo_trainer_config:
      data:
        max_prompt_length: 3072
        max_response_length: 3072
      actor_rollout_ref:
        actor:
          ppo_max_token_len_per_gpu: 6144
          ppo_micro_batch_size_per_gpu: 2
        ref:
          log_prob_micro_batch_size_per_gpu: 2
          log_prob_max_token_len_per_gpu: 6144
        rollout:
          temperature: 0.6
          prompt_length: 3072
          response_length: 3072
          max_num_batched_tokens: 6144
          max_num_seqs: 96
