defaults:
- search_mas_nosearch_external
- _self_

training:
  total_training_steps: 50
  project_name: orchrl
  experiment_name: search_mas_train_50step_improved
  logger:
  - console
  model_checkpoints_dir: checkpoints/search_mas_train_50step_improved
  train_batch_size: 8
  train_sample_num: 16
  validate_sample_num: 4
  val_freq: 10

models:
  model_0:
    ppo_trainer_config:
      actor_rollout_ref:
        actor:
          ppo_max_token_len_per_gpu: 8192
        ref:
          log_prob_micro_batch_size_per_gpu: 8
          log_prob_max_token_len_per_gpu: 8192
        rollout:
          max_num_batched_tokens: 8192
          max_num_seqs: 128
  model_1:
    ppo_trainer_config:
      actor_rollout_ref:
        actor:
          ppo_max_token_len_per_gpu: 8192
        ref:
          log_prob_micro_batch_size_per_gpu: 8
          log_prob_max_token_len_per_gpu: 8192
        rollout:
          max_num_batched_tokens: 8192
          max_num_seqs: 128
  model_2:
    ppo_trainer_config:
      actor_rollout_ref:
        actor:
          ppo_max_token_len_per_gpu: 8192
        ref:
          log_prob_micro_batch_size_per_gpu: 8
          log_prob_max_token_len_per_gpu: 8192
        rollout:
          max_num_batched_tokens: 8192
          max_num_seqs: 128
